services:
  ergos-api:
    build: "./backend"
#      context: .
#      dockerfile: backend/Dockerfile
    ports:
      - 5000:5000
    restart: always
        
  db:
    image: mariadb
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ergos
      - MYSQL_USER=ergos_admin
      - MYSQL_PASSWORD=ergos123
    expose:
      - 3306
    ports:
      - 3566:3306
  frontend:
    build: "./frontend"
    ports:
      - 4200:80
